<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>create_match_loop_with_open_match_betting_and_resulting_ASC</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>3c161d62-38de-4421-a8b7-afc0845d482d</testSuiteGuid>
   <testCaseLink>
      <guid>6e6dcdd2-9a75-4d10-a8cd-d49a873b0e90</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Backoffice/create_match/create_match_loop_with_open_match_betting_and_resulting_ASC</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f19db9bb-f616-45ca-9bc7-aabaa6fbe9e7</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/match_ASC</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>f19db9bb-f616-45ca-9bc7-aabaa6fbe9e7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Meron_Name</value>
         <variableId>2c0e2acf-c538-47af-9f38-b313a5c51381</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f19db9bb-f616-45ca-9bc7-aabaa6fbe9e7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Meron_Farm</value>
         <variableId>9f78306a-476b-4838-a382-18eecda8d086</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f19db9bb-f616-45ca-9bc7-aabaa6fbe9e7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Meron_Breed</value>
         <variableId>fe140a88-3de8-44b2-925c-35ba11cb0a25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f19db9bb-f616-45ca-9bc7-aabaa6fbe9e7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Meron_Weight</value>
         <variableId>dd36124a-8abc-4201-be6b-8035fdc3ddaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f19db9bb-f616-45ca-9bc7-aabaa6fbe9e7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Wala_Name</value>
         <variableId>71494e7b-6dfa-40b7-a3ee-ea10355e6ea8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f19db9bb-f616-45ca-9bc7-aabaa6fbe9e7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Wala_Farm</value>
         <variableId>554a727f-b68a-4c08-83ba-1a2b0ccdab9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f19db9bb-f616-45ca-9bc7-aabaa6fbe9e7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Wala_Breed</value>
         <variableId>4d234718-83a0-4a8b-bc5c-976ca1deb058</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f19db9bb-f616-45ca-9bc7-aabaa6fbe9e7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Wala_Weight</value>
         <variableId>321ae6c6-f4c5-498f-8dd0-5d57c6431c1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f19db9bb-f616-45ca-9bc7-aabaa6fbe9e7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Arena_Acronym </value>
         <variableId>c86601be-3948-4524-a254-64b0490192f5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
