<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>create_arena_15</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-11-26T09:23:34</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>9cbfe692-7b25-436c-b485-f03d07e693c3</testSuiteGuid>
   <testCaseLink>
      <guid>39e2a095-66fe-4d89-81b2-c615ee4918af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Backoffice/create_arena/create_arena</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b92f9cfb-9e41-4ab1-af7b-cec9bda4eb89</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Backoffice/match_details</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>aa1650f3-a823-446c-9eaa-39ca5afec5ed</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Backoffice/arena_details</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>b92f9cfb-9e41-4ab1-af7b-cec9bda4eb89</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Arena_Name</value>
         <variableId>59327247-ddf5-4913-a596-e932d1e68ac6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>aa1650f3-a823-446c-9eaa-39ca5afec5ed</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Event_Name</value>
         <variableId>04f8e467-24b9-4429-972e-03c74b055995</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>aa1650f3-a823-446c-9eaa-39ca5afec5ed</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Acronym</value>
         <variableId>910d3e19-c890-482f-afe4-53c04633fd8a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>aa1650f3-a823-446c-9eaa-39ca5afec5ed</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Profit_Margin</value>
         <variableId>813df0cc-4e39-4cf2-907c-866f6409290e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
